[package]
name = "blades"
version = "0.1.4"
authors = ["Maroš Grego <maros@grego.site>"]
edition = "2018"
description = "Blazing fast dead simple static site generator"
repository = "https://github.com/grego/blades"
keywords = ["website", "site", "generator"]
categories = ["command-line-utilities", "web-programming"]
license = "GPL-3.0-or-later"
readme = "README.md"
homepage = "https://www.getblades.org"

[dependencies]
ramhorns = "0.11"
arrayvec = { version = "0.7.1", features = ["serde"] }
beef = { version = "0.5", features = ["impl_serde"]}
serde = { version = "1.0.126", features = ["derive"] }
chrono = { version = "0.4.19", features = ["clock", "serde"], default_features = false }
ahash = "0.7.3"
parking_lot = "0.11.1"
toml = "0.5.8"
rayon = "1.5.1"
structopt = "0.3.21"
thiserror = "1.0.26"

[profile.release]
lto = true

[profile.bench]
lto = true
