title = "My site!"

[plugins]
input = ["cat input.json"]
transform = ["../target/release/examples/transform_plugin"]
output = ["dd status=none of=pages.json"]

[plugins.content]
erase = "echo \"hahaha erased\""
