title = "About"
plugins = ["erase"]
content = """
Tuvan throat singing, Khoomei, is one particular variant of overtone singing practiced by people in Tuva and Siberia. In 2009, it was inscribed on the Representative List of the Intangible Cultural Heritage of Humanity of UNESCO.
"""
